name: Terraform Validation

on:
  push:
    branches: [ master, multi-server-architecture ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "~1.0"
        
    - name: Terraform Format Check
      run: |
        cd terraform
        terraform fmt -check -recursive
        
    - name: Terraform Init
      run: |
        cd terraform
        terraform init -backend=false
        
    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate
        
    - name: Terraform Plan (Dry Run)
      run: |
        cd terraform
        terraform plan -var="key_name=test-key"
      env:
        TF_VAR_key_name: "test-key"